# Generated by Django 2.2.3 on 2019-07-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('gst_no', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=25, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=85)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
